export const prioritiesActionTypes = {
  GET_PRIOIRITIES_START: "GET_PRIOIRITIES_START",
  GET_PRIOIRITIES_SUCCESS: "GET_PRIOIRITIES_SUCCESS",
  GET_PRIOIRITIES_FAILURE: "GET_PRIOIRITIES_FAILURE",
  ADD_PRIORITY_START: "ADD_PRIORITY_START",
  ADD_PRIORITY_SUCCESS: "ADD_PRIORITY_SUCCESS",
  ADD_PRIORITY_FAILURE: "ADD_PRIORITY_FAILURE",
  DELETE_PRIORITY_START: "DELETE_PRIORITY_START",
  DELETE_PRIORITY_SUCCESS: "DELETE_PRIORITY_SUCCESS",
  DELETE_PRIORITY_FAILURE: "DELETE_PRIORITY_FAILURE",
  UPDATE_PRIORITY_START: "UPDATE_PRIORITY_START",
  UPDATE_PRIORITY_SUCCESS: "UPDATE_PRIORITY_SUCCESS",
  UPDATE_PRIORITY_FAILURE: "UPDATE_PRIORITY_FAILURE",
};
